{
  pkgs,
  targetPkgs ? pkgs,
  lib,
  config,
  version,
  firmwarePackage,
}: let
  diskId = "0x6d616e61";
  partUuidA = "6d616e61-02";
  partUuidB = "6d616e61-03";

  envOffsetSectors = 1024;
  envRedundantOffsetSectors = 1536;
  envSizeBytes = 256 * 1024;
  firstPartitionSectorOffset = 2048;

  firmwareSizeMiB = 256;
  persistentSeedSizeMiB = 256;

  ubootPackage = targetPkgs.ubootRaspberryPi3_64bit.override {
    extraConfig = ''
      CONFIG_ENV_IS_IN_MMC=y
      CONFIG_ENV_OFFSET=0x80000
      CONFIG_ENV_OFFSET_REDUND=0xC0000
      CONFIG_ENV_SIZE=0x40000
      CONFIG_SYS_REDUNDAND_ENVIRONMENT=y
      CONFIG_CMD_SAVEENV=y
      CONFIG_CMD_FOR=y
      CONFIG_CMD_SETEXPR=y
      CONFIG_CMD_SYSBOOT=y
      CONFIG_HUSH_PARSER=y
    '';
  };

  bootScriptSource = pkgs.writeText "boot.txt" ''
    setenv scriptaddr 0x02400000

    test -n "''${BOOT_ORDER}" || setenv BOOT_ORDER "A B"
    test -n "''${BOOT_A_LEFT}" || setenv BOOT_A_LEFT 3
    test -n "''${BOOT_B_LEFT}" || setenv BOOT_B_LEFT 3

    setenv slot_chosen 0

    for slot in ''${BOOT_ORDER}; do
        if test "''${slot_chosen}" = "0" && test "''${slot}" = "A" && test "''${BOOT_A_LEFT}" -gt 0; then
            echo "Booting slot A (''${BOOT_A_LEFT} attempts left)"
            setexpr BOOT_A_LEFT ''${BOOT_A_LEFT} - 1
            saveenv
            setenv slot_chosen 1
            sysboot mmc 0:2 any ''${scriptaddr} /boot/extlinux/extlinux.conf
        fi
        if test "''${slot_chosen}" = "0" && test "''${slot}" = "B" && test "''${BOOT_B_LEFT}" -gt 0; then
            echo "Booting slot B (''${BOOT_B_LEFT} attempts left)"
            setexpr BOOT_B_LEFT ''${BOOT_B_LEFT} - 1
            saveenv
            setenv slot_chosen 1
            sysboot mmc 0:3 any ''${scriptaddr} /boot/extlinux/extlinux.conf
        fi
    done

    echo "ERROR: All boot slots are exhausted. Power-cycle the device or"
    echo "       boot from a recovery SD to reflash the factory image."
  '';

  bootScript =
    pkgs.runCommand "boot.scr" {
      nativeBuildInputs = [pkgs.ubootTools];
    } ''
      mkimage -A arm64 -O linux -T script -C none -n "Manafishrov A/B boot" \
        -d ${bootScriptSource} "$out"
    '';

  slotPartuuid = slot:
    if slot == "A"
    then partUuidA
    else partUuidB;

  slotIndex = slot:
    if slot == "A"
    then "2"
    else "3";

  patchExtlinuxForSlot = slot: ''
    conf="./files/boot/extlinux/extlinux.conf"
    if [ ! -f "$conf" ]; then
      echo "ERROR: extlinux.conf not generated by installBootLoader" >&2
      exit 1
    fi

    if ! grep -q '^[[:space:]]*APPEND ' "$conf"; then
      echo "ERROR: extlinux.conf has no APPEND line" >&2
      exit 1
    fi

    ${pkgs.gnused}/bin/sed -i \
      '/^[[:space:]]*APPEND /s|$| rauc.slot=${slot} root=PARTUUID=${slotPartuuid slot}|' \
      "$conf"

    if ! grep -q 'rauc\.slot=${slot}' "$conf"; then
      echo "ERROR: extlinux.conf patch for slot ${slot} failed" >&2
      cat "$conf" >&2
      exit 1
    fi
  '';

  rootfsForSlot = slot:
    pkgs.callPackage (pkgs.path + "/nixos/lib/make-ext4-fs.nix") {
      storePaths = [config.system.build.toplevel];
      volumeLabel = "ROOT_${slot}";
      uuid = "6d616e61-000${slotIndex slot}-4000-8000-00000000000${slotIndex slot}";
      populateImageCommands = ''
        mkdir -p ./files/boot
        ${config.boot.loader.raspberryPi.bootPopulateCmd} -c ${config.system.build.toplevel} -b ./files/boot
        ${patchExtlinuxForSlot slot}
      '';
    };

  firmwarePartition =
    pkgs.runCommand "firmware-partition.img" {
      nativeBuildInputs = [pkgs.dosfstools pkgs.mtools pkgs.coreutils];
    } ''
          set -euo pipefail
          img="$out"
          truncate -s ${toString firmwareSizeMiB}MiB "$img"
          mkfs.vfat -n FIRMWARE -F 32 "$img"

          mcopy -i "$img" -s ${firmwarePackage}/share/raspberrypi/firmware/* ::/
          mcopy -i "$img" ${ubootPackage}/u-boot.bin ::/u-boot.bin
          mcopy -i "$img" ${bootScript} ::/boot.scr

          cat > config.txt <<'PICONF'
      [all]
      enable_uart=1
      arm_64bit=1
      kernel=u-boot.bin
      PICONF
          mcopy -i "$img" config.txt ::/config.txt
    '';

  envPrimary =
    pkgs.runCommand "uboot-env-primary.bin" {
      nativeBuildInputs = [pkgs.ubootTools pkgs.coreutils];
    } ''
          cat > env.txt <<'UENV'
      BOOT_ORDER=A B
      BOOT_A_LEFT=3
      BOOT_B_LEFT=3
      UENV
          mkenvimage -r -s 0x${lib.toHexString envSizeBytes} -o "$out" env.txt
    '';

  persistentSeed =
    pkgs.runCommand "persistent-seed.img" {
      nativeBuildInputs = [pkgs.e2fsprogs];
    } ''
      truncate -s ${toString persistentSeedSizeMiB}MiB "$out"
      mkfs.ext4 -L PERSISTENT -U 6d616e61-0004-4000-8000-000000000004 "$out"
    '';

  rootfsA = rootfsForSlot "A";
  rootfsB = rootfsForSlot "B";

  sdImage =
    pkgs.runCommand "manafishrov-${version}.img" {
      nativeBuildInputs = [pkgs.parted pkgs.util-linux pkgs.coreutils pkgs.zstd];
      passthru = {inherit version partUuidA partUuidB;};
    } ''
          set -euo pipefail
          img=image.img

          firmware_size=$(stat -c %s ${firmwarePartition})
          root_a_size=$(stat -c %s ${rootfsA})
          root_b_size=$(stat -c %s ${rootfsB})
          persistent_size=$(stat -c %s ${persistentSeed})

          sector=512
          align_sectors=$((1024 * 1024 / sector))

          p1_start=${toString firstPartitionSectorOffset}
          p1_sectors=$(( (firmware_size + sector - 1) / sector ))
          p1_sectors=$(( ((p1_sectors + align_sectors - 1) / align_sectors) * align_sectors ))

          p2_start=$(( p1_start + p1_sectors ))
          p2_sectors=$(( (root_a_size + sector - 1) / sector ))
          p2_sectors=$(( ((p2_sectors + align_sectors - 1) / align_sectors) * align_sectors ))

          p3_start=$(( p2_start + p2_sectors ))
          p3_sectors=$(( (root_b_size + sector - 1) / sector ))
          p3_sectors=$(( ((p3_sectors + align_sectors - 1) / align_sectors) * align_sectors ))

          p4_start=$(( p3_start + p3_sectors ))
          p4_sectors=$(( (persistent_size + sector - 1) / sector ))
          p4_sectors=$(( ((p4_sectors + align_sectors - 1) / align_sectors) * align_sectors ))

          total_sectors=$(( p4_start + p4_sectors + align_sectors ))

          truncate -s $(( total_sectors * sector )) "$img"

          sfdisk "$img" <<SFDISK
      label: dos
      label-id: ${diskId}
      unit: sectors
      sector-size: 512

      start=$p1_start, size=$p1_sectors, type=c, name=FIRMWARE
      start=$p2_start, size=$p2_sectors, type=83, bootable, name=ROOT_A
      start=$p3_start, size=$p3_sectors, type=83, name=ROOT_B
      start=$p4_start, size=$p4_sectors, type=83, name=PERSISTENT
      SFDISK

          dd if=${envPrimary} of="$img" bs=512 seek=${toString envOffsetSectors} conv=notrunc status=none
          dd if=${envPrimary} of="$img" bs=512 seek=${toString envRedundantOffsetSectors} conv=notrunc status=none

          dd if=${firmwarePartition} of="$img" bs=512 seek=$p1_start conv=notrunc status=none
          dd if=${rootfsA} of="$img" bs=512 seek=$p2_start conv=notrunc status=none
          dd if=${rootfsB} of="$img" bs=512 seek=$p3_start conv=notrunc status=none
          dd if=${persistentSeed} of="$img" bs=512 seek=$p4_start conv=notrunc status=none

          mkdir -p "$out"
          cp "$img" "$out/manafishrov-${version}.img"
          zstd -19 -T0 -o "$out/manafishrov-${version}.img.zst" "$out/manafishrov-${version}.img"
    '';

  bundleRootfsImage = pkgs.callPackage (pkgs.path + "/nixos/lib/make-ext4-fs.nix") {
    storePaths = [config.system.build.toplevel];
    volumeLabel = "ROOT_BUNDLE";
    populateImageCommands = ''
      mkdir -p ./files/boot
      ${config.boot.loader.raspberryPi.bootPopulateCmd} -c ${config.system.build.toplevel} -b ./files/boot
    '';
  };

  raucBundle =
    pkgs.runCommand "manafishrov-${version}-rauc-bundle" {
      nativeBuildInputs = [pkgs.rauc pkgs.coreutils];
      passthru = {
        inherit version;
        bundleName = "manafishrov-${version}.raucb";
      };
    } ''
          set -euo pipefail

          if [ -z "''${RAUC_SIGNING_KEY_PATH:-}" ] || [ -z "''${RAUC_SIGNING_CERT_PATH:-}" ]; then
            echo "ERROR: RAUC_SIGNING_KEY_PATH and RAUC_SIGNING_CERT_PATH must point to PEM files." >&2
            exit 1
          fi

          workdir="$(mktemp -d)"
          trap 'rm -rf "$workdir"' EXIT

          cp "${bundleRootfsImage}" "$workdir/rootfs.img"
          chmod u+w "$workdir/rootfs.img"

          rootfs_size_bytes="$(stat -c %s "$workdir/rootfs.img")"
          rootfs_sha256="$(sha256sum "$workdir/rootfs.img" | awk '{print $1}')"

          cat > "$workdir/manifest.raucm" <<MANIFEST
      [update]
      compatible=manafishrov-pi3
      version=${version}
      description=Manafishrov firmware ${version}

      [bundle]
      format=verity

      [image.rootfs]
      filename=rootfs.img
      size=$rootfs_size_bytes
      sha256=$rootfs_sha256
      MANIFEST

          mkdir -p "$out"
          rauc bundle \
            --cert="$RAUC_SIGNING_CERT_PATH" \
            --key="$RAUC_SIGNING_KEY_PATH" \
            "$workdir" \
            "$out/manafishrov-${version}.raucb"
    '';
in {
  inherit sdImage raucBundle;
}
