"""Constants used throughout the firmware."""

from pathlib import Path
import re
from typing import Final


# Thruster
THRUSTER_INPUT_START_BYTE: Final = 0x5A
MCU_CONFIG_START_BYTE: Final = 0xC5
MCU_VERSION_START_BYTE: Final = 0xD5
MCU_PROTOCOL_PWM: Final = 0
MCU_PROTOCOL_DSHOT: Final = 1
MCU_VERSION_PACKET_SIZE: Final = 8
MCU_FIRST_BOOT_RETRY_LIMIT: Final = 5
MCU_TELEMETRY_STALE_TIMEOUT_S: Final = 3.0
NUM_MOTORS: Final = 8
THRUSTER_NEUTRAL_PULSE_WIDTH: Final = 1000
THRUSTER_FORWARD_PULSE_RANGE: Final = 1000
THRUSTER_REVERSE_PULSE_RANGE: Final = 1000
THRUSTER_TIMEOUT_MS: Final = 200
THRUSTER_POLES: Final = 14
THRUSTER_TEST_DURATION_SECONDS: Final = 10
THRUSTER_SEND_FREQUENCY: Final = 120

# Regulator
DEPTH_DERIVATIVE_EMA_TAU: Final = 0.064
PITCH_MAX: Final = 80
MAX_AUTO_TUNING_ROLL_PITCH_DEGREES: Final = 10
INTEGRAL_WINDUP_CLIP_DEGREES: Final = 100
AUTO_TUNING_ZERO_THRESHOLD_DEGREES: Final = 3
AUTO_TUNING_AMPLITUDE_THRESHOLD_DEGREES: Final = 30
AUTO_TUNING_ZERO_THRESHOLD_DEPTH_METERS: Final = 0.1
AUTO_TUNING_AMPLITUDE_THRESHOLD_DEPTH_METERS: Final = 0.5
AUTO_TUNING_OSCILLATION_DURATION_SECONDS: Final = 10
AHRS_MAHONY_KP: Final = 1.5
AHRS_MAHONY_KI: Final = 0.05
AHRS_ACCEL_MIN_NORM: Final = 1e-3
DEPTH_INTEGRAL_WINDUP_CLIP: Final = 3.0
INTEGRAL_RELAX_THRESHOLD: Final = 0.2
MAX_GYRO_DEG_PER_SEC: Final = 1080.0

# IMU
IMU_READ_FREQUENCY: Final = 120

# Pressure sensor
PRESSURE_SENSOR_READ_FREQUENCY: Final = 100

# MCU Telemetry
MCU_TELEMETRY_START_BYTE: Final = 0xA5
MCU_TELEMETRY_PACKET_SIZE: Final = 8
MCU_TELEMETRY_BATCH_START_BYTE: Final = 0xA6
MCU_TELEMETRY_BATCH_ENTRY_SIZE: Final = 6
MCU_TELEMETRY_BATCH_MAX_ITEMS: Final = 16
MCU_TELEMETRY_TYPE_ERPM: Final = 0
MCU_TELEMETRY_TYPE_VOLTAGE: Final = 1
MCU_TELEMETRY_TYPE_TEMPERATURE: Final = 2
MCU_TELEMETRY_TYPE_CURRENT: Final = 3
MCU_TELEMETRY_TYPE_SIGNAL_QUALITY: Final = 4
LOG_PACKET_START_BYTE: Final = 0xB5
LOG_PACKET_HEADER_SIZE: Final = 3
LOG_LEVEL_INFO: Final = 0
LOG_LEVEL_WARN: Final = 1
LOG_LEVEL_ERROR: Final = 2
MOTORS_PER_BUS: Final = 4

# Toast IDs
THRUSTER_TEST_TOAST_ID: Final = "thruster-test"
AUTO_TUNING_TOAST_ID: Final = "regulator-auto-tuning"
FLASH_TOAST_ID: Final = "flash-mcu-firmware"
FIRMWARE_UPDATE_TOAST_ID: Final = "firmware-update"

# Firmware update
FIRMWARE_UPDATE_PORT: Final = 9100
FIRMWARE_UPDATE_DIR: Final = Path("/var/lib/manafish-firmware-update")
FIRMWARE_UPDATE_REQUEST_PATH: Final = FIRMWARE_UPDATE_DIR / "request.json"
FIRMWARE_UPDATE_STATUS_PATH: Final = FIRMWARE_UPDATE_DIR / "status.json"
FIRMWARE_UPDATE_MAX_HEADER_BYTES: Final = 64 * 1024
FIRMWARE_UPDATE_CHUNK_SIZE: Final = 1024 * 1024
FIRMWARE_UPDATE_FREE_SPACE_MARGIN_BYTES: Final = 512 * 1024 * 1024
FIRMWARE_UPDATE_NIX_SYSTEM_PATH_RE: Final[re.Pattern[str]] = re.compile(
    r"^/nix/store/[a-z0-9]{32}-nixos-system-.+"
)

# General
SYSTEM_FAILURE_THRESHOLD: Final = 3
