"""Constants used throughout the firmware."""

from typing import Final


# General
FIRMWARE_VERSION: Final = "1.0.0"

# Thruster
THRUSTER_INPUT_START_BYTE: Final = 0x5A
NUM_MOTORS: Final = 8
THRUSTER_NEUTRAL_PULSE_WIDTH: Final = 1000
THRUSTER_FORWARD_PULSE_RANGE: Final = 1000
THRUSTER_REVERSE_PULSE_RANGE: Final = 1000
THRUSTER_TIMEOUT_MS: Final = 200
THRUSTER_POLES: Final = 14
THRUSTER_TEST_DURATION_SECONDS: Final = 10
THRUSTER_SEND_FREQUENCY: Final = 120

# Regulator
DEPTH_DERIVATIVE_EMA_TAU: Final = 0.064
PITCH_MAX: Final = 80
MAX_AUTO_TUNING_ROLL_PITCH_DEGREES: Final = 10
INTEGRAL_WINDUP_CLIP_DEGREES: Final = 100
AUTO_TUNING_ZERO_THRESHOLD_DEGREES: Final = 3
AUTO_TUNING_AMPLITUDE_THRESHOLD_DEGREES: Final = 30
AUTO_TUNING_ZERO_THRESHOLD_DEPTH_METERS: Final = 0.1
AUTO_TUNING_AMPLITUDE_THRESHOLD_DEPTH_METERS: Final = 0.5
AUTO_TUNING_OSCILLATION_DURATION_SECONDS: Final = 10
AHRS_MAHONY_KP: Final = 1.5
AHRS_MAHONY_KI: Final = 0.05
AHRS_ACCEL_MIN_NORM: Final = 1e-3
DEPTH_INTEGRAL_WINDUP_CLIP: Final = 3.0
INTEGRAL_RELAX_THRESHOLD: Final = 0.2
MAX_GYRO_DEG_PER_SEC: Final = 1080.0

# IMU
IMU_READ_FREQUENCY: Final = 120

# Pressure sensor
PRESSURE_SENSOR_READ_FREQUENCY: Final = 100

# ESC
ESC_TELEMETRY_START_BYTE: Final = 0xA5
ESC_TELEMETRY_PACKET_SIZE: Final = 8
ESC_MAX_READ_BUFFER_SIZE: Final = 16
ESC_PACKET_TYPE_ERPM: Final = 0
ESC_PACKET_TYPE_VOLTAGE: Final = 1
ESC_PACKET_TYPE_TEMPERATURE: Final = 2
ESC_PACKET_TYPE_CURRENT: Final = 3
ESC_PACKET_TYPE_STRESS: Final = 4
MAX_CURRENT_A: Final = 2.5
BATTERY_EMA_ALPHA: Final = 0.1

# Toast IDs
THRUSTER_TEST_TOAST_ID: Final = "thruster-test"
AUTO_TUNING_TOAST_ID: Final = "regulator-auto-tuning"
FLASH_TOAST_ID: Final = "flash-microcontroller-firmware"

# General
SYSTEM_FAILURE_THRESHOLD: Final = 3


# Websocket
IP_ADDRESS: Final = "10.10.10.10"
PORT: Final = 9000
