"""Constants used throughout the firmware."""

# General
FIRMWARE_VERSION = "1.0.0"

# Thruster
THRUSTER_INPUT_START_BYTE = 0x5A
NUM_MOTORS = 8
THRUSTER_NEUTRAL_PULSE_WIDTH = 1000
THRUSTER_FORWARD_PULSE_RANGE = 1000
THRUSTER_REVERSE_PULSE_RANGE = 1000
THRUSTER_TIMEOUT_MS = 200
THRUSTER_POLES = 14
THRUSTER_TEST_DURATION_SECONDS = 10
THRUSTER_SEND_FREQUENCY = 60

# Regulator
DEPTH_DERIVATIVE_EMA_TAU = 0.064
PITCH_MAX = 90
MAX_AUTO_TUNING_ROLL_PITCH_DEGREES = 10
INTEGRAL_WINDUP_CLIP_DEGREES = 100
AUTO_TUNING_ZERO_THRESHOLD_DEGREES = 3
AUTO_TUNING_AMPLITUDE_THRESHOLD_DEGREES = 30
AUTO_TUNING_ZERO_THRESHOLD_DEPTH_METERS = 0.1
AUTO_TUNING_AMPLITUDE_THRESHOLD_DEPTH_METERS = 0.5
AUTO_TUNING_OSCILLATION_DURATION_SECONDS = 10
AHRS_MAHONY_KP: float = 2.5
AHRS_MAHONY_KI: float = 0.05
AHRS_ACCEL_MIN_NORM: float = 1e-3
DT_MIN_SECONDS: float = 1e-3
DT_MAX_SECONDS: float = 0.1
DEPTH_INTEGRAL_WINDUP_CLIP: float = 3.0
INTEGRAL_RELAX_THRESHOLD: float = 0.2

# IMU
IMU_READ_FREQUENCY = 100

# Pressure sensor
PRESSURE_SENSOR_READ_FREQUENCY = 50

# ESC
ESC_TELEMETRY_START_BYTE = 0xA5
ESC_TELEMETRY_PACKET_SIZE = 8
ESC_MAX_READ_BUFFER_SIZE = 16
ESC_PACKET_TYPE_ERPM = 0
ESC_PACKET_TYPE_VOLTAGE = 1
ESC_PACKET_TYPE_TEMPERATURE = 2
ESC_PACKET_TYPE_CURRENT = 3
ESC_PACKET_TYPE_STRESS = 4
MAX_CURRENT_A = 2.5
BATTERY_EMA_ALPHA = 0.1

# Toast IDs
THRUSTER_TEST_TOAST_ID = "thruster-test"
AUTO_TUNING_TOAST_ID = "regulator-auto-tuning"
FLASH_TOAST_ID = "flash-microcontroller-firmware"

# General
SYSTEM_FAILURE_THRESHOLD = 3


# Websocket
IP_ADDRESS = "10.10.10.10"
PORT = 9000
